import 'package:json_annotation/json_annotation.dart';
import 'job_item_model.dart';
import 'user_model.dart';

// part 'job_model.g.dart';  // Generated by build_runner - enable after integration

@JsonSerializable()
class Job {
  final String id;
  @JsonKey(name: 'customer_id')
  final String customerId;
  final Customer? customer;
  @JsonKey(name: 'items')
  final List<JobItem>? items;
  @JsonKey(name: 'rider_id')
  final String? riderId;
  final User? rider;
  @JsonKey(name: 'pickup_location')
  final Location pickupLocation;
  @JsonKey(name: 'dropoff_location')
  final Location dropoffLocation;
  @JsonKey(name: 'item_description')
  final String itemDescription;
  @JsonKey(name: 'item_weight')
  final double? itemWeight;
  final String urgency; // urgent, normal, scheduled
  @JsonKey(name: 'estimated_fare')
  final double estimatedFare;
  @JsonKey(name: 'platform_charge')
  final double? platformCharge;
  @JsonKey(name: 'total_price')
  final double? totalPrice;
  final String status; // posted, accepted, picked_up, delivered, cancelled
  @JsonKey(name: 'payment_status')
  final String paymentStatus; // pending, paid, refunded
  final double? rating;
  final String? review;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Job({
    required this.id,
    required this.customerId,
    this.customer,
    this.items,
    this.riderId,
    this.rider,
    required this.pickupLocation,
    required this.dropoffLocation,
    required this.itemDescription,
    this.itemWeight,
    required this.urgency,
    required this.estimatedFare,
    this.platformCharge,
    this.totalPrice,
    required this.status,
    required this.paymentStatus,
    this.rating,
    this.review,
    required this.createdAt,
    required this.updatedAt,
  });

  // factory Job.fromJson(Map<String, dynamic> json) => _$JobFromJson(json);
  // Map<String, dynamic> toJson() => _$JobToJson(this);

  // Manual JSON serialization for Navigator
  Map<String, dynamic> toJson() => {
    'id': id,
    // Map Flutter customerId to Laravel user_id
    'user_id': customerId,
    'customer_id': customerId,
    'customerId': customerId,
    'customer': customer?.toJson(),
    'rider_id': riderId,
    'riderId': riderId,
    'rider': rider?.toJson(),
    // Flatten location objects for Laravel API
    'pickup_address': pickupLocation.address,
    'pickupLocation': pickupLocation.toJson(),
    'pickup_location': pickupLocation.toJson(),
    'items': items?.map((item) => item.toJson()).toList(),
    'pickup_lat': pickupLocation.latitude,
    'pickup_latitude': pickupLocation.latitude,
    'pickup_lng': pickupLocation.longitude,
    'pickup_longitude': pickupLocation.longitude,
    'dropoff_address': dropoffLocation.address,
    'dropoffLocation': dropoffLocation.toJson(),
    'dropoff_location': dropoffLocation.toJson(),
    'dropoff_lat': dropoffLocation.latitude,
    'dropoff_latitude': dropoffLocation.latitude,
    'dropoff_lng': dropoffLocation.longitude,
    'dropoff_longitude': dropoffLocation.longitude,
    // Map Flutter itemDescription to Laravel title
    'title': itemDescription,
    'item_description': itemDescription,
    'itemDescription': itemDescription,
    'description': itemDescription,
    'item_weight': itemWeight,
    'urgency': urgency,
    // Map Flutter estimatedFare to Laravel price
    'price': estimatedFare,
    'estimated_fare': estimatedFare,
    'estimatedFare': estimatedFare,
    'platform_charge': platformCharge,
    'platformCharge': platformCharge,
    'total_price': totalPrice,
    'totalPrice': totalPrice,
    // Map Flutter status to Laravel status
    'status': mapFlutterStatusToLaravel(status),
    'payment_status': paymentStatus,
    'paymentStatus': paymentStatus,
    'rating': rating,
    'review': review,
    'created_at': createdAt.toIso8601String(),
    'updated_at': updatedAt.toIso8601String(),
  };

  // Manual JSON deserialization until code generation is enabled
  static Job fromJson(Map<String, dynamic> json) {
    // Handle location deserialization - locations might be nested objects or separate fields
    Map<String, dynamic> pickupLocationMap;
    if (json['pickupLocation'] is Map) {
      // Already a nested object from serialization
      pickupLocationMap = json['pickupLocation'] as Map<String, dynamic>;
    } else if (json['pickup_location'] is Map) {
      // Nested object from API
      pickupLocationMap = json['pickup_location'] as Map<String, dynamic>;
    } else {
      // Separate fields from API or after serialization
      pickupLocationMap = {
        'latitude': json['pickupLocation.latitude'] ?? json['pickup_lat'],  // Preserve null if not provided
        'longitude': json['pickupLocation.longitude'] ?? json['pickup_lng'],  // Preserve null if not provided
        'address': json['pickupLocation.address'] ?? json['pickup_address'] ?? 'Pickup Location',
        'place_id': json['pickupLocation.placeId'] ?? json['pickup_place_id'],
      };
    }

    Map<String, dynamic> dropoffLocationMap;
    if (json['dropoffLocation'] is Map) {
      // Already a nested object from serialization
      dropoffLocationMap = json['dropoffLocation'] as Map<String, dynamic>;
    } else if (json['dropoff_location'] is Map) {
      // Nested object from API
      dropoffLocationMap = json['dropoff_location'] as Map<String, dynamic>;
    } else {
      // Separate fields from API or after serialization
      dropoffLocationMap = {
        'latitude': json['dropoffLocation.latitude'] ?? json['dropoff_lat'],  // Preserve null if not provided
        'longitude': json['dropoffLocation.longitude'] ?? json['dropoff_lng'],  // Preserve null if not provided
        'address': json['dropoffLocation.address'] ?? json['dropoff_address'] ?? 'Dropoff Location',
        'place_id': json['dropoffLocation.placeId'] ?? json['dropoff_place_id'],
      };
    }

    final customerJson = json['customer'] ?? json['user'];
    final customerIdValue = json['user_id']?.toString()
        ?? json['customer_id']?.toString()
        ?? json['customerId']?.toString()
        ?? (customerJson is Map ? customerJson['id']?.toString() : null)
        ?? '';

    return Job(
      id: json['id']?.toString() ?? '',
      // Laravel uses user_id for job creator, map to customerId in Flutter
      customerId: customerIdValue,
      customer: customerJson != null
          ? Customer.fromJson(customerJson as Map<String, dynamic>)
          : null,
      // Laravel handles rider assignment through JobApplication, not direct riderId
      riderId: json['rider_id']?.toString() ??
          json['riderId']?.toString() ??
          _extractRiderId(json),
      rider: json['rider'] != null
          ? User.fromJson(json['rider'] as Map<String, dynamic>)
          : _extractRiderJson(json) != null
              ? User.fromJson(_extractRiderJson(json)!)
              : null,
      items: (json['items'] is List)
          ? (json['items'] as List).map((item) {
              if (item is Map<String, dynamic>) {
                return JobItem.fromJson(item);
              }
              if (item is Map) {
                return JobItem.fromJson(Map<String, dynamic>.from(item));
              }
              return JobItem.fromJson({});
            }).toList()
          : null,
      pickupLocation: Location.fromJson(pickupLocationMap),
      dropoffLocation: Location.fromJson(dropoffLocationMap),
      // Laravel uses 'title' for job description, Flutter expects 'itemDescription'
      itemDescription: json['title']?.toString() ?? json['item_description']?.toString() ?? json['itemDescription']?.toString() ?? json['description']?.toString() ?? '',
      itemWeight: json['item_weight'] != null ? double.tryParse(json['item_weight'].toString()) : null,
      urgency: json['urgency']?.toString() ?? 'normal',
      // Laravel uses 'price' for fare, Flutter expects 'estimatedFare'
      estimatedFare: (json['price'] ?? json['estimated_fare'] ?? json['estimatedFare']) != null
          ? double.tryParse(json['price']?.toString() ?? json['estimated_fare']?.toString() ?? json['estimatedFare']?.toString() ?? '0') ?? 0.0
          : 0.0,
      platformCharge: json['platform_charge'] != null
          ? double.tryParse(json['platform_charge'].toString())
          : (json['platformCharge'] != null ? double.tryParse(json['platformCharge'].toString()) : null),
      totalPrice: json['total_price'] != null
          ? double.tryParse(json['total_price'].toString())
          : (json['totalPrice'] != null ? double.tryParse(json['totalPrice'].toString()) : null),
      // Map Laravel status 'open' to Flutter 'posted'
      status: _mapLaravelStatusToFlutter(json['status']?.toString() ?? 'open'),
      paymentStatus: json['payment_status']?.toString() ?? json['paymentStatus']?.toString() ?? 'pending',
      rating: json['rating'] != null ? double.tryParse(json['rating'].toString()) : null,
      review: json['review']?.toString(),
      createdAt: json['created_at'] != null 
          ? DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.tryParse(json['updated_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
    );
  }
}

Map<String, dynamic>? _extractRiderJson(Map<String, dynamic> json) {
  if (json['rider'] is Map) {
    return Map<String, dynamic>.from(json['rider'] as Map);
  }

  if (json['user_rider'] is Map) {
    return Map<String, dynamic>.from(json['user_rider'] as Map);
  }

  if (json['userRider'] is Map) {
    return Map<String, dynamic>.from(json['userRider'] as Map);
  }

  if (json['applications'] is List) {
    for (final app in json['applications'] as List) {
      if (app is Map<String, dynamic>) {
        final appStatus = app['status']?.toString().toLowerCase() ?? '';
        if (['accepted', 'in_progress', 'picked_up', 'delivered']
            .contains(appStatus)) {
          if (app['user_rider'] is Map) {
            return Map<String, dynamic>.from(app['user_rider'] as Map);
          }
          if (app['userRider'] is Map) {
            return Map<String, dynamic>.from(app['userRider'] as Map);
          }
          if (app['rider'] is Map) {
            return Map<String, dynamic>.from(app['rider'] as Map);
          }
          if (app['user_rider_id'] != null || app['rider_id'] != null) {
            final name = app['rider_name']?.toString() ?? '';
            final parts = name.split(' ');
            return {
              'id': app['user_rider_id']?.toString() ?? app['rider_id']?.toString() ?? '',
              'first_name': parts.isNotEmpty ? parts.first : '',
              'last_name': parts.length > 1 ? parts.sublist(1).join(' ') : '',
              'email': app['rider_email']?.toString() ?? '',
              'mobile_number': app['rider_phone']?.toString() ?? '',
              'avatar': app['rider_avatar']?.toString() ?? '',
              'user_type': 'rider',
              'is_verified': false,
              'created_at': DateTime.now().toIso8601String(),
              'updated_at': DateTime.now().toIso8601String(),
            };
          }
        }
      }
    }
  }

  return null;
}

String? _extractRiderId(Map<String, dynamic> json) {
  final riderJson = _extractRiderJson(json);
  if (riderJson != null && riderJson['id'] != null) {
    return riderJson['id']?.toString();
  }

  if (json['applications'] is List) {
    for (final app in json['applications'] as List) {
      if (app is Map<String, dynamic>) {
        final appStatus = app['status']?.toString().toLowerCase() ?? '';
        if (['accepted', 'in_progress', 'picked_up', 'delivered']
            .contains(appStatus)) {
          return app['user_rider_id']?.toString() ?? app['rider_id']?.toString();
        }
      }
    }
  }

  return null;
}

/// Maps Laravel job status values to Flutter job status values
String _mapLaravelStatusToFlutter(String laravelStatus) {
  switch (laravelStatus.toLowerCase()) {
    case 'open':
      return 'posted';
    case 'matched':
    case 'accepted':
      return 'accepted';
    case 'in_progress':
      return 'in_progress';
    case 'picked_up':
      return 'picked_up';
    case 'completed':
    case 'delivered':
      return 'delivered';
    case 'cancelled':
      return 'cancelled';
    default:
      return 'posted';
  }
}

/// Maps Flutter job status values to Laravel job status values
String mapFlutterStatusToLaravel(String flutterStatus) {
  switch (flutterStatus.toLowerCase()) {
    case 'posted':
      return 'open';
    case 'accepted':
      return 'matched';
    case 'picked_up':
      return 'in_progress';
    case 'delivered':
      return 'completed';
    case 'cancelled':
      return 'cancelled';
    default:
      return 'open';
  }
}

@JsonSerializable()
class Location {
  final double? latitude;      // Nullable - coordinates optional
  final double? longitude;     // Nullable - coordinates optional
  final String address;
  @JsonKey(name: 'place_id')
  final String? placeId;

  Location({
    this.latitude,             // Optional parameter
    this.longitude,            // Optional parameter
    required this.address,
    this.placeId,
  });

  // factory Location.fromJson(Map<String, dynamic> json) =>
  //     _$LocationFromJson(json);
  // Map<String, dynamic> toJson() => _$LocationToJson(this);

  Map<String, dynamic> toJson() => {
    'latitude': latitude,
    'longitude': longitude,
    'address': address,
    'place_id': placeId,
  };

  static Location fromJson(Map<String, dynamic> json) {
    // Safely parse latitude - handle both string and numeric values from API
    double? latitude;
    if (json['latitude'] != null) {
      if (json['latitude'] is String) {
        latitude = double.tryParse(json['latitude'] as String);
      } else if (json['latitude'] is num) {
        latitude = (json['latitude'] as num).toDouble();
      }
    }
    
    // Safely parse longitude - handle both string and numeric values from API
    double? longitude;
    if (json['longitude'] != null) {
      if (json['longitude'] is String) {
        longitude = double.tryParse(json['longitude'] as String);
      } else if (json['longitude'] is num) {
        longitude = (json['longitude'] as num).toDouble();
      }
    }
    
    return Location(
      latitude: latitude,
      longitude: longitude,
      address: json['address']?.toString() ?? '',
      placeId: json['place_id']?.toString(),
    );
  }

  /// Check if this location has valid coordinates
  bool get hasCoordinates => latitude != null && longitude != null;
  
  /// Get coordinates as a string, or return 'Address only' if not available
  String get coordinateString {
    if (hasCoordinates) {
      return '$latitude, $longitude';
    }
    return 'Address only';
  }
}

@JsonSerializable()
class Customer {
  final String id;
  final String email;
  @JsonKey(name: 'first_name')
  final String firstName;
  @JsonKey(name: 'last_name')
  final String lastName;
  final String? phone;
  final String? avatar;
  final double? rating;

  Customer({
    required this.id,
    required this.email,
    required this.firstName,
    required this.lastName,
    this.phone,
    this.avatar,
    this.rating,
  });

  String get fullName => '$firstName $lastName';

  // factory Customer.fromJson(Map<String, dynamic> json) =>
  //     _$CustomerFromJson(json);
  // Map<String, dynamic> toJson() => _$CustomerToJson(this);

  Map<String, dynamic> toJson() => {
    'id': id,
    'email': email,
    'first_name': firstName,
    'last_name': lastName,
    'phone': phone,
    'avatar': avatar,
    'rating': rating,
  };

  static Customer fromJson(Map<String, dynamic> json) {
    return Customer(
      id: json['id']?.toString() ?? '',
      email: json['email']?.toString() ?? '',
      firstName: json['first_name']?.toString() ?? '',
      lastName: json['last_name']?.toString() ?? '',
      phone: json['phone']?.toString() ?? json['mobile_number']?.toString() ?? json['mobile']?.toString(),
      avatar: json['avatar']?.toString(),
      rating: json['rating'] != null ? double.tryParse(json['rating'].toString()) : null,
    );
  }
}
