import 'package:json_annotation/json_annotation.dart';
import 'job_model.dart';

// part 'job_application_model.g.dart';  // Generated by build_runner - enable after integration

@JsonSerializable()
class JobApplication {
  final String id;
  @JsonKey(name: 'job_id')
  final String jobId;
  @JsonKey(name: 'rider_id')
  final String riderId;
  @JsonKey(name: 'rider_name')
  final String? riderName;
  @JsonKey(name: 'rider_avatar')
  final String? riderAvatar;
  @JsonKey(name: 'offered_price')
  final double? offeredPrice;
  final String? status; // pending, accepted, rejected
  @JsonKey(name: 'message')
  final String? riderMessage;
  final Job? job;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  JobApplication({
    required this.id,
    required this.jobId,
    required this.riderId,
    this.riderName,
    this.riderAvatar,
    this.offeredPrice,
    this.status,
    this.riderMessage,
    this.job,
    required this.createdAt,
    required this.updatedAt,
  });

  factory JobApplication.fromJson(Map<String, dynamic> json) {
    return JobApplication(
      id: json['id']?.toString() ?? '',
      jobId: json['job_id']?.toString() ?? '',
      riderId: json['rider_id']?.toString() ?? '',
      riderName: json['rider_name'] as String?,
      riderAvatar: json['rider_avatar'] as String?,
      offeredPrice: json['offered_price'] != null
          ? double.tryParse(json['offered_price'].toString())
          : null,
      status: json['status'] as String?,
      riderMessage: json['message'] as String?,
      job: json['job'] != null && json['job'] is Map
          ? Job.fromJson(Map<String, dynamic>.from(json['job'] as Map))
          : null,
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.tryParse(json['updated_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'job_id': jobId,
      'rider_id': riderId,
      'rider_name': riderName,
      'rider_avatar': riderAvatar,
      'offered_price': offeredPrice,
      'status': status,
      'message': riderMessage,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  // Map<String, dynamic> toJson() => _$JobApplicationToJson(this);
}
