import 'package:json_annotation/json_annotation.dart';

// part 'message_model.g.dart';  // Generated by build_runner - enable after integration

@JsonSerializable()
class ChatMessage {
  final String id;
  @JsonKey(name: 'sender_id')
  final String senderId;
  @JsonKey(name: 'receiver_id')
  final String receiverId;
  final String message;
  @JsonKey(name: 'is_read')
  final bool isRead;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;
  final String? senderName;
  final String? senderAvatar;
  @JsonKey(name: 'attachment_url')
  final String? attachmentUrl;
  @JsonKey(name: 'attachment_type')
  final String? attachmentType;

  ChatMessage({
    required this.id,
    required this.senderId,
    required this.receiverId,
    required this.message,
    this.isRead = false,
    required this.createdAt,
    this.senderName,
    this.senderAvatar,
    this.attachmentUrl,
    this.attachmentType,
  });

  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    return ChatMessage(
      id: json['id']?.toString() ?? DateTime.now().millisecondsSinceEpoch.toString(),
      senderId: json['sender_id']?.toString() ?? json['senderId']?.toString() ?? '',
      receiverId: json['receiver_id']?.toString() ?? json['receiverId']?.toString() ?? '',
      message: json['message']?.toString() ?? '',
      isRead: json['is_read'] == true || json['isRead'] == true,
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
      senderName: json['sender_name']?.toString() ?? json['senderName']?.toString(),
      senderAvatar: json['sender_avatar']?.toString() ?? json['senderAvatar']?.toString(),
      attachmentUrl: json['attachment_url']?.toString() ?? json['attachmentUrl']?.toString(),
      attachmentType: json['attachment_type']?.toString() ?? json['attachmentType']?.toString(),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'sender_id': senderId,
        'receiver_id': receiverId,
        'message': message,
        'is_read': isRead,
        'created_at': createdAt.toIso8601String(),
        'sender_name': senderName,
        'sender_avatar': senderAvatar,
        'attachment_url': attachmentUrl,
        'attachment_type': attachmentType,
      };

  // factory ChatMessage.fromJson(Map<String, dynamic> json) =>
  //     _$ChatMessageFromJson(json);
  // Map<String, dynamic> toJson() => _$ChatMessageToJson(this);
}

@JsonSerializable()
class ChatThread {
  final String id;
  @JsonKey(name: 'user_id_1')
  final String userId1;
  @JsonKey(name: 'user_id_2')
  final String userId2;
  @JsonKey(name: 'last_message')
  final String? lastMessage;
  @JsonKey(name: 'last_message_time')
  final DateTime? lastMessageTime;
  @JsonKey(name: 'unread_count')
  final int unreadCount;
  final String? otherUserName;
  final String? otherUserAvatar;

  ChatThread({
    required this.id,
    required this.userId1,
    required this.userId2,
    this.lastMessage,
    this.lastMessageTime,
    this.unreadCount = 0,
    this.otherUserName,
    this.otherUserAvatar,
  });

  factory ChatThread.fromJson(Map<String, dynamic> json) {
    return ChatThread(
      id: json['id']?.toString() ?? DateTime.now().millisecondsSinceEpoch.toString(),
      userId1: json['user_id_1']?.toString() ?? json['userId1']?.toString() ?? '',
      userId2: json['user_id_2']?.toString() ?? json['userId2']?.toString() ?? '',
      lastMessage: json['last_message']?.toString() ?? json['lastMessage']?.toString(),
      lastMessageTime: json['last_message_time'] != null
          ? DateTime.tryParse(json['last_message_time'].toString())
          : null,
      unreadCount: int.tryParse(json['unread_count']?.toString() ?? '') ?? 0,
      otherUserName: json['other_user_name']?.toString() ?? json['otherUserName']?.toString(),
      otherUserAvatar: json['other_user_avatar']?.toString() ?? json['otherUserAvatar']?.toString(),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'user_id_1': userId1,
        'user_id_2': userId2,
        'last_message': lastMessage,
        'last_message_time': lastMessageTime?.toIso8601String(),
        'unread_count': unreadCount,
        'other_user_name': otherUserName,
        'other_user_avatar': otherUserAvatar,
      };

  // factory ChatThread.fromJson(Map<String, dynamic> json) =>
  //     _$ChatThreadFromJson(json);
  // Map<String, dynamic> toJson() => _$ChatThreadToJson(this);
}
