import 'package:json_annotation/json_annotation.dart';

// part 'user_model.g.dart';  // Generated by build_runner - enable after integration

@JsonSerializable()
class User {
  final String id;
  final String email;
  @JsonKey(name: 'first_name')
  final String firstName;
  @JsonKey(name: 'last_name')
  final String lastName;
  final String phone;
  final String? avatar;
  @JsonKey(name: 'user_type')
  final UserType userType;
  @JsonKey(name: 'kyc_status')
  final KYCStatus? kycStatus;
  @JsonKey(name: 'is_verified')
  final bool isVerified;
  @JsonKey(name: 'rider_profile_id')
  final String? riderProfileId;
  @JsonKey(name: 'rider_profile_status')
  final String? riderProfileStatus;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  User({
    required this.id,
    required this.email,
    required this.firstName,
    required this.lastName,
    required this.phone,
    this.avatar,
    required this.userType,
    this.kycStatus,
    this.isVerified = false,
    this.riderProfileId,
    this.riderProfileStatus,
    required this.createdAt,
    required this.updatedAt,
  });

  String get fullName => '$firstName $lastName';

  // factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
  // Map<String, dynamic> toJson() => _$UserToJson(this);

  Map<String, dynamic> toJson() => {
    'id': id,
    'email': email,
    'first_name': firstName,
    'last_name': lastName,
    'mobile_number': phone,
    'avatar': avatar,
    'user_type': userType.toString().split('.').last,
    'kyc_status': kycStatus?.toString().split('.').last,
    'is_verified': isVerified,
    'rider_profile_id': riderProfileId,
    'rider_profile_status': riderProfileStatus,
    'created_at': createdAt.toIso8601String(),
    'updated_at': updatedAt.toIso8601String(),
  };

  static User fromJson(Map<String, dynamic> json) {
    UserType userType = UserType.customer;
    try {
      final typeStr = json['user_type']?.toString().toLowerCase() ?? 'customer';
      userType = typeStr == 'rider' ? UserType.rider : UserType.customer;
    } catch (_) {
      userType = UserType.customer;
    }

    KYCStatus? kycStatus;
    try {
      final statusStr = json['kyc_status']?.toString().toLowerCase();
      if (statusStr == 'approved') {
        kycStatus = KYCStatus.approved;
      } else if (statusStr == 'rejected') {
        kycStatus = KYCStatus.rejected;
      } else if (statusStr == 'pending') {
        kycStatus = KYCStatus.pending;
      }
    } catch (_) {}

    return User(
      id: json['id']?.toString() ?? '',
      email: json['email']?.toString() ?? '',
      firstName: json['first_name']?.toString() ?? '',
      lastName: json['last_name']?.toString() ?? '',
      phone: json['phone']?.toString() ?? json['mobile_number']?.toString() ?? json['mobile']?.toString() ?? '',
      avatar: json['avatar']?.toString(),
      userType: userType,
      kycStatus: kycStatus,
      isVerified: json['is_verified'] == true || json['is_verified'] == 1,
      riderProfileId: _extractRiderProfileId(json),
      riderProfileStatus: _extractRiderProfileStatus(json),
      createdAt: json['created_at'] != null
          ? DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
      updatedAt: json['updated_at'] != null
          ? DateTime.tryParse(json['updated_at'].toString()) ?? DateTime.now()
          : DateTime.now(),
    );
  }

  static String? _extractRiderProfileId(Map<String, dynamic> json) {
    final profile = json['rider_profile'] ?? json['riderProfile'];
    if (profile is Map<String, dynamic>) {
      return profile['id']?.toString();
    }
    return json['rider_profile_id']?.toString() ?? json['riderProfileId']?.toString();
  }

  static String? _extractRiderProfileStatus(Map<String, dynamic> json) {
    final profile = json['rider_profile'] ?? json['riderProfile'];
    if (profile is Map<String, dynamic>) {
      return profile['status']?.toString();
    }
    return json['rider_profile_status']?.toString() ?? json['riderProfileStatus']?.toString();
  }
}

enum UserType { customer, rider }

enum KYCStatus { pending, approved, rejected }

@JsonSerializable()
class AuthResponse {
  final String token;
  final User user;
  @JsonKey(name: 'refresh_token')
  final String? refreshToken;

  AuthResponse({
    required this.token,
    required this.user,
    this.refreshToken,
  });

  // factory AuthResponse.fromJson(Map<String, dynamic> json) =>
  //     _$AuthResponseFromJson(json);
  // Map<String, dynamic> toJson() => _$AuthResponseToJson(this);
}
