import 'package:json_annotation/json_annotation.dart';

// part 'wallet_model.g.dart';  // Generated by build_runner - enable after integration

@JsonSerializable()
class Wallet {
  final String id;
  @JsonKey(name: 'rider_id')
  final String riderId;
  final double balance;
  final double totalEarnings;
  @JsonKey(name: 'total_withdrawn')
  final double totalWithdrawn;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Wallet({
    required this.id,
    required this.riderId,
    required this.balance,
    required this.totalEarnings,
    required this.totalWithdrawn,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Wallet.fromJson(Map<String, dynamic> json) {
    final payload = json['data'] is Map<String, dynamic> ? json['data'] as Map<String, dynamic> : json;

    return Wallet(
      id: payload['id']?.toString() ?? payload['wallet_id']?.toString() ?? '',
      riderId: payload['rider_id']?.toString() ?? payload['wallet_no']?.toString() ?? '',
      balance: double.tryParse(payload['balance']?.toString() ?? '0') ?? 0.0,
      totalEarnings: double.tryParse(payload['total_earnings']?.toString() ?? '0') ?? 0.0,
      totalWithdrawn: double.tryParse(payload['total_withdrawn']?.toString() ?? '0') ?? 0.0,
      createdAt: DateTime.tryParse(payload['created_at']?.toString() ?? '') ?? DateTime.now(),
      updatedAt: DateTime.tryParse(payload['updated_at']?.toString() ?? '') ?? DateTime.now(),
    );
  }

  // factory Wallet.fromJson(Map<String, dynamic> json) => _$WalletFromJson(json);
  // Map<String, dynamic> toJson() => _$WalletToJson(this);
}

@JsonSerializable()
class Transaction {
  final String id;
  @JsonKey(name: 'wallet_id')
  final String walletId;
  @JsonKey(name: 'job_id')
  final String? jobId;
  @JsonKey(name: 'transaction_type')
  final String transactionType;
  final String purpose;
  final String type; // earning, withdrawal, refund
  final double amount;
  final String status; // pending, completed, failed
  final String? description;
  final String? comment;
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  Transaction({
    required this.id,
    required this.walletId,
    this.jobId,
    required this.transactionType,
    required this.purpose,
    required this.type,
    required this.amount,
    required this.status,
    this.description,
    this.comment,
    required this.createdAt,
  });

  factory Transaction.fromJson(Map<String, dynamic> json) {
    final data = json['data'] is Map<String, dynamic>
        ? json['data'] as Map<String, dynamic>
        : json;

    final transactionType = data['transaction_type']?.toString() ??
        data['type']?.toString() ??
        'unknown';
    final purpose = data['purpose']?.toString() ?? '';
    final status = data['status']?.toString() ??
        (purpose == 'withdrawal' ? 'pending' : 'completed');
    final description = data['comment']?.toString() ??
        data['description']?.toString();

    return Transaction(
      id: data['id']?.toString() ?? '',
      walletId: data['wallet_id']?.toString() ?? '',
      jobId: data['job_id']?.toString(),
      transactionType: transactionType,
      purpose: purpose,
      type: purpose.isNotEmpty ? purpose : transactionType,
      amount: double.tryParse(data['amount']?.toString() ?? '0') ?? 0.0,
      status: status,
      description: description,
      comment: data['comment']?.toString(),
      createdAt: DateTime.tryParse(data['created_at']?.toString() ?? '') ?? DateTime.now(),
    );
  }

  // factory Transaction.fromJson(Map<String, dynamic> json) =>
  //     _$TransactionFromJson(json);
  // Map<String, dynamic> toJson() => _$TransactionToJson(this);
}

@JsonSerializable()
class Withdrawal {
  final String id;
  @JsonKey(name: 'wallet_id')
  final String walletId;
  final double amount;
  @JsonKey(name: 'bank_name')
  final String bankName;
  @JsonKey(name: 'account_number')
  final String accountNumber;
  @JsonKey(name: 'account_name')
  final String accountName;
  final String status; // pending, completed, failed
  @JsonKey(name: 'created_at')
  final DateTime createdAt;
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Withdrawal({
    required this.id,
    required this.walletId,
    required this.amount,
    required this.bankName,
    required this.accountNumber,
    required this.accountName,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  // factory Withdrawal.fromJson(Map<String, dynamic> json) =>
  //     _$WithdrawalFromJson(json);
  // Map<String, dynamic> toJson() => _$WithdrawalToJson(this);
}

class AppNotification {
  final String id;
  final String? type;
  final String title;
  final String body;
  final bool isRead;
  final DateTime createdAt;
  final Map<String, dynamic>? payload;

  AppNotification({
    required this.id,
    this.type,
    required this.title,
    required this.body,
    required this.isRead,
    required this.createdAt,
    this.payload,
  });

  factory AppNotification.fromJson(Map<String, dynamic> json) {
    final payload = json['payload'] is Map<String, dynamic>
        ? json['payload'] as Map<String, dynamic>
        : null;

    return AppNotification(
      id: json['id']?.toString() ?? '',
      type: json['type']?.toString(),
      title: json['title']?.toString() ?? (payload != null ? payload['title']?.toString() : '') ?? '',
      body: json['body']?.toString() ?? (payload != null ? payload['body']?.toString() : '') ?? '',
      isRead: json['is_read'] == true || json['is_read']?.toString() == '1',
      createdAt: DateTime.tryParse(json['created_at']?.toString() ?? '') ?? DateTime.now(),
      payload: payload,
    );
  }
}
